INSERT INTO hotpot(name, img, description)
VALUES
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Bouncy Fishball', 'https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/e8/39/85/e839858f-7711-e2ab-ce36-a906bfe527a9/source/512x512bb.jpg', 'White bouncy succulent handmade Fishball. Made with Spanish Mackerel and LOVE'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Wagyu Beef', 'https://media.lasvegasweekly.com/img/photos/2012/09/05/japanese_beef_by_jon_sperry_t1000.jpg', 'Highly prized snow-aged Wagyu beef. Incredibly tender with buttery soft flavour'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Chicken', 'https://previews.123rf.com/images/deuxrondo/deuxrondo1607/deuxrondo160700013/60315389-translation-of-japanese-is-year-of-the-chicken.jpg', 'Japan Miyazaki prefecture Jitokko free-range chicken. Unparalleled flavour with a refreshing taste'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Hon-Maguro', 'https://1.bp.blogspot.com/-9rwzrwbhtbM/V9Akv2JXKiI/AAAAAAAB65Y/uEiIxBR11oY8Ned90jgjUL5QwhOZWyy0wCLcB/s1600/maguro%2Bheader.png', 'Bluefin Tuna prized for rich, buttery, umami flavour'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Broccoli', 'https://i.pinimg.com/originals/ea/e6/f7/eae6f712bd3e01ed1637c4e752c3342d.jpg', 'Australia Broccoli. A great source of vitamins K and C'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Carrot', 'https://i.pinimg.com/originals/46/48/8b/46488b3bfb1e0f3d700820f5edd22297.jpg', 'Good for Bugs Bunny, good for you. Rich vitamin A & antioxidants'),
('Lobster', 'https://i.pinimg.com/originals/19/e9/9b/19e99bc7b00b8811e0b17cf22335dd9d.jpg', 'Ise-ebi, Japanese Spiny Lobster. Rich, full and sweet flavour with a succulent texture'),
('Lobster', 'https://i.pinimg.com/originals/19/e9/9b/19e99bc7b00b8811e0b17cf22335dd9d.jpg', 'Ise-ebi, Japanese Spiny Lobster. Rich, full and sweet flavour with a succulent texture'),
('Lobster', 'https://i.pinimg.com/originals/19/e9/9b/19e99bc7b00b8811e0b17cf22335dd9d.jpg', 'Ise-ebi, Japanese Spiny Lobster. Rich, full and sweet flavour with a succulent texture'),
('Lobster', 'https://i.pinimg.com/originals/19/e9/9b/19e99bc7b00b8811e0b17cf22335dd9d.jpg', 'Ise-ebi, Japanese Spiny Lobster. Rich, full and sweet flavour with a succulent texture'),
('Bitter gourd', 'https://cdn.dribbble.com/users/1698559/screenshots/3483427/gourd.png', 'Bitter gourd or bitter melon. Love it or hate it'),
('Bitter gourd', 'https://cdn.dribbble.com/users/1698559/screenshots/3483427/gourd.png', 'Bitter gourd or bitter melon. Love it or hate it'),
('Bitter gourd', 'https://cdn.dribbble.com/users/1698559/screenshots/3483427/gourd.png', 'Bitter gourd or bitter melon. Love it or hate it'),
('Bitter gourd', 'https://cdn.dribbble.com/users/1698559/screenshots/3483427/gourd.png', 'Bitter gourd or bitter melon. Love it or hate it'),
('Bitter gourd', 'https://cdn.dribbble.com/users/1698559/screenshots/3483427/gourd.png', 'Bitter gourd or bitter melon. Love it or hate it'),
('Bitter gourd', 'https://cdn.dribbble.com/users/1698559/screenshots/3483427/gourd.png', 'Bitter gourd or bitter melon. Love it or hate it'),
('Cute Tofu', 'https://image.spreadshirtmedia.com/image-server/v1/compositions/108341543/views/1,width=650,height=650,appearanceId=63,version=1565757568/a-kawaii-cartoon-of-a-smiley-tofu-asking-people-to-love-tofu-a-fun-and-cute-design-for-vegans-health-and-tofu-lovers.jpg', 'Silken soft tofu and a good source of protein'),
('Cute Tofu', 'https://image.spreadshirtmedia.com/image-server/v1/compositions/108341543/views/1,width=650,height=650,appearanceId=63,version=1565757568/a-kawaii-cartoon-of-a-smiley-tofu-asking-people-to-love-tofu-a-fun-and-cute-design-for-vegans-health-and-tofu-lovers.jpg', 'Silken soft tofu and a good source of protein'),
('Cute Tofu', 'https://image.spreadshirtmedia.com/image-server/v1/compositions/108341543/views/1,width=650,height=650,appearanceId=63,version=1565757568/a-kawaii-cartoon-of-a-smiley-tofu-asking-people-to-love-tofu-a-fun-and-cute-design-for-vegans-health-and-tofu-lovers.jpg', 'Silken soft tofu and a good source of protein'),
('Cute Tofu', 'https://image.spreadshirtmedia.com/image-server/v1/compositions/108341543/views/1,width=650,height=650,appearanceId=63,version=1565757568/a-kawaii-cartoon-of-a-smiley-tofu-asking-people-to-love-tofu-a-fun-and-cute-design-for-vegans-health-and-tofu-lovers.jpg', 'Silken soft tofu and a good source of protein'),
('Cute Tofu', 'https://image.spreadshirtmedia.com/image-server/v1/compositions/108341543/views/1,width=650,height=650,appearanceId=63,version=1565757568/a-kawaii-cartoon-of-a-smiley-tofu-asking-people-to-love-tofu-a-fun-and-cute-design-for-vegans-health-and-tofu-lovers.jpg', 'Silken soft tofu and a good source of protein'),
('Cute Tofu', 'https://image.spreadshirtmedia.com/image-server/v1/compositions/108341543/views/1,width=650,height=650,appearanceId=63,version=1565757568/a-kawaii-cartoon-of-a-smiley-tofu-asking-people-to-love-tofu-a-fun-and-cute-design-for-vegans-health-and-tofu-lovers.jpg', 'Silken soft tofu and a good source of protein');

INSERT INTO action(name, img, description, type)
VALUES
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Dont touch my food', 'https://media-cdn.tripadvisor.com/media/photo-s/15/1c/72/6f/don-t-touch-my-food.jpg', 'Protect against Snatching, Swapping and Force', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Deflecting', 'https://qph.fs.quoracdn.net/main-qimg-d96f231628273251a024dc1ba3bc586f', 'Deflect against Snatching and Force. You may choose another target player', 'defensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Snatching', 'https://pics.me.me/happiness-is-snatching-food-from-your-friends-9648395.png', 'Target a player and choose a food from targeted player plate.', 'offensive'),
('Swapping', 'https://millcityfarmersmarket.org/wp-content/uploads/2011/02/hands-exchanging-radishes.jpg','Exchange your plate with targeted player plate', 'offensive'),
('Swapping', 'https://millcityfarmersmarket.org/wp-content/uploads/2011/02/hands-exchanging-radishes.jpg','Exchange your plate with targeted player plate', 'offensive'),
('Swapping', 'https://millcityfarmersmarket.org/wp-content/uploads/2011/02/hands-exchanging-radishes.jpg','Exchange your plate with targeted player plate', 'offensive'),
('Swapping', 'https://millcityfarmersmarket.org/wp-content/uploads/2011/02/hands-exchanging-radishes.jpg','Exchange your plate with targeted player plate', 'offensive'),
('Swapping', 'https://millcityfarmersmarket.org/wp-content/uploads/2011/02/hands-exchanging-radishes.jpg','Exchange your plate with targeted player plate', 'offensive'),
('Swapping', 'https://millcityfarmersmarket.org/wp-content/uploads/2011/02/hands-exchanging-radishes.jpg','Exchange your plate with targeted player plate', 'offensive'),
('Force', 'https://uploads1.bundoo.com/wp-content/uploads/2014/04/Why-you-need-to-practice-responsive-feeding-800x500.jpg', 'Give a food of yours to a targeted player. He or she must eat it.', 'offensive'),
('Force', 'https://uploads1.bundoo.com/wp-content/uploads/2014/04/Why-you-need-to-practice-responsive-feeding-800x500.jpg', 'Give a food of yours to a targeted player. He or she must eat it.', 'offensive'),
('Force', 'https://uploads1.bundoo.com/wp-content/uploads/2014/04/Why-you-need-to-practice-responsive-feeding-800x500.jpg', 'Give a food of yours to a targeted player. He or she must eat it.', 'offensive'),
('Force', 'https://uploads1.bundoo.com/wp-content/uploads/2014/04/Why-you-need-to-practice-responsive-feeding-800x500.jpg', 'Give a food of yours to a targeted player. He or she must eat it.', 'offensive'),
('Force', 'https://uploads1.bundoo.com/wp-content/uploads/2014/04/Why-you-need-to-practice-responsive-feeding-800x500.jpg', 'Give a food of yours to a targeted player. He or she must eat it.', 'offensive');